# Generated by Django 4.2.3 on 2023-07-15 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('status', models.CharField(choices=[('order placed', 'order placed'), ('deliverd', 'delivered'), ('cancel', 'cancel'), ('out for delivery', 'out for delivery'), ('shipped', 'shipped')], default='order placed', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.craft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='cart', max_length=100)),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.craft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
